// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Services.ProductAPI.AppDbContext;

#nullable disable

namespace Restaurant.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Restaurant.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Beef",
                            Description = "Burger with cheese",
                            ImageURL = "https://cdn-image.foodandwine.com/sites/default/files/200306-r-xl-classic-beef-burgers.jpg",
                            Name = "Cheeseburger",
                            Price = 14.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Beef",
                            Description = "Burger with peanut butter",
                            ImageURL = "https://cdn-image.foodandwine.com/sites/default/files/200306-r-xl-classic-beef-burgers.jpg",
                            Name = "Butterheaven",
                            Price = 17.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Chicken",
                            Description = "Glazed with Korean sauce",
                            ImageURL = "https://simply-delicious-food.com/wp-content/uploads/2018/11/spicy-chicken-burgers-3.jpg",
                            Name = "Korean Fried Chicken",
                            Price = 16.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Chicken",
                            Description = "Chicken burger",
                            ImageURL = "https://simply-delicious-food.com/wp-content/uploads/2018/11/spicy-chicken-burgers-3.jpg",
                            Name = "Bok Bok",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
