<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewSystem.Domain\InterviewSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="InterviewProcesses\CreateInterviewProcess\" />
    <Folder Include="InterviewProcesses\GetInterviewProcessDetails\" />
    <Folder Include="InterviewProcesses\GetInterviewProcessesSummary\" />
    <Folder Include="InterviewRounds\CreateInterviewRound\" />
    <Folder Include="InterviewRounds\GetInterviewRoundDetails\" />
    <Folder Include="InterviewRounds\GetInterviewRoundsSummary\" />
    <Folder Include="InterviewTasks\CreateInterviewTask\" />
    <Folder Include="InterviewTasks\GetInterviewTaskDetails\" />
    <Folder Include="InterviewTasks\GetInterviewTasksSummary\" />
  </ItemGroup>

</Project>
