<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewSystem.Domain\InterviewSystem.Domain.csproj" />
    <ProjectReference Include="..\InterviewSystem.Infrastructure\InterviewSystem.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Employees\DeactivateEmployee\" />
    <Folder Include="Employees\GetEmployeeDetails\" />
    <Folder Include="Employees\GetEmployeeByDepartment\" />
    <Folder Include="Employees\UpdateEmployee\" />
  </ItemGroup>

</Project>
