<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewSystem.Domain\InterviewSystem.Domain.csproj" />
    <ProjectReference Include="..\InterviewSystem.Infrastructure\InterviewSystem.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Employee\" />
    <Folder Include="DTOs\InterviewProcess\" />
    <Folder Include="DTOs\InterviewRound\" />
    <Folder Include="DTOs\InterviewTask\" />
  </ItemGroup>

</Project>
