// <auto-generated />
using System;
using InterviewSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215111918_dropped-InterviewRound-NumberOfRounds-column-retry")]
    partial class droppedInterviewRoundNumberOfRoundscolumnretry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewSystem.Domain.Entity.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliedPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("InterviewSystem.Domain.Entity.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeDepartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeePosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InterviewSystem.Domain.Entity.InterviewProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentInterviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentInterviewerName")
                        .HasColumnType("text");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterviewProcessStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InterviewProcesses");
                });

            modelBuilder.Entity("InterviewSystem.Domain.Entity.InterviewRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InterviewRounds");
                });

            modelBuilder.Entity("InterviewSystem.Domain.Entity.InterviewTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewRoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("InterviewTaskStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Rejected")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskRejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("InterviewRoundId");

                    b.ToTable("InterviewTasks");
                });

            modelBuilder.Entity("InterviewSystem.Domain.Entity.InterviewRound", b =>
                {
                    b.OwnsMany("InterviewSystem.Domain.Entity.InterviewRoundItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("InterviewRoundId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("InterviewRoundId", "Sequence")
                                .IsUnique();

                            b1.ToTable("InterviewRoundItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InterviewRoundId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("InterviewSystem.Domain.Entity.InterviewTask", b =>
                {
                    b.HasOne("InterviewSystem.Domain.Entity.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewSystem.Domain.Entity.InterviewRound", null)
                        .WithMany()
                        .HasForeignKey("InterviewRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("InterviewSystem.Domain.Entity.CandidateEvaluation", "Evaluation", b1 =>
                        {
                            b1.Property<Guid>("InterviewTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Note")
                                .HasColumnType("text")
                                .HasColumnName("EvaluationNote");

                            b1.Property<bool>("Passed")
                                .HasColumnType("boolean")
                                .HasColumnName("EvaluationPassed");

                            b1.HasKey("InterviewTaskId");

                            b1.ToTable("InterviewTasks");

                            b1.WithOwner()
                                .HasForeignKey("InterviewTaskId");
                        });

                    b.Navigation("Evaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
